exclude: '^docs/conf.py$|^\.virtual_documents/'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace #removes trailing whitespace
      - id: check-added-large-files #prevents addition of large files
      - id: check-ast #Checks that Python files can be parsed as abstract syntax trees (important for
      #ensuring Python files have no syntax errors and for additional security and workflow issues)
      - id: check-json #validates JSON files for correctness
      - id: check-merge-conflict #prevents committing files with merge conflict markers
      - id: check-xml #validates XML files for correctness.
      - id: check-yaml #Validates YAML files for correctness (e.g., comments start with #, style guidelines,
      #syntax validation)
      - id: debug-statements
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: mixed-line-ending
        args: ['--fix=auto']  # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows


  ## If you want to automatically "modernize" your Python code:
  # - repo: https://github.com/asottile/pyupgrade
  #   rev: v3.10.1
  #   - id: pyupgrade
  #  hooks:
  #    args: ['--py37-plus']
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
    - id: nbqa-black
    - id: nbqa-pyupgrade
      args: ["--py37-plus"]
    - id: nbqa-isort
      args: ["--float-to-top"]

  # If you want to avoid flake8 errors due to unused vars or imports:
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.1.1
    hooks:
    - id: autoflake
      args: [
       --in-place,
       --remove-all-unused-imports,
       --remove-unused-variables,
        ]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    - id: isort

  #formats python code
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    - id: black
      args: [--line-length=120]
      language_version: python3.11


  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    - id: flake8
    ## You can add flake8 plugins via `additional_dependencies`:
    #  additional_dependencies: [flake8-bugbear]


  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-mock-methods
      - id: python-use-type-annotations
      - id: python-check-blanket-noqa
      - id: python-use-type-annotations
      - id: text-unicode-replacement-char

 #-   repo: https://github.com/pre-commit/mirrors-mypy
 #    rev: '08cbc46'  # Use the sha / tag you want to point at
 #    hooks:
 #    -   id: mypy
